#!/usr/bin/with-contenv bash

echo "**** installing php ****"
apt-get update && \
apt-get install -y lsb-release ca-certificates apt-transport-https software-properties-common && \
add-apt-repository -y ppa:ondrej/php && \
apt-get update && \
apt-get install -y php8.0 php8.0-gd php8.0-zip php8.0-bcmath
