#!/usr/bin/with-contenv bash

echo "**** installing php ****"
apt-get update && \
apt-get install -y lsb-release apt-transport-https ca-certificates && \
curl https://packages.sury.org/php/apt.gpg --output /etc/apt/trusted.gpg.d/php.gpg --silent && \
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" >> /etc/apt/sources.list.d/php.list  && \
apt-get update && \
apt-get install -y php8.0 php8.0-gd php8.0-zip php8.0-bcmath
