#!/usr/bin/with-contenv bash

echo "**** installing php ****"
apt-get update && \
apt-get install -y lsb-release ca-certificates apt-transport-https software-properties-common unzip && \
add-apt-repository -y ppa:ondrej/php && \
apt-get update && \
apt-get install -y php8.0-cli php8.0-gd php8.0-zip php8.0-bcmath php8.0-mbstring php8.0-curl php8.0-redis php8.0-sqlite3 php8.0-xml
